# =========================================
# Application
# =========================================
spring.application.name=pos-service
server.port=8080

# =========================================
# H2 DATABASE (DEV / TEST)
# Enable only when needed
# =========================================
# spring.datasource.url=jdbc:h2:mem:posdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true


# =========================================
# MYSQL DATABASE (PROD / LOCAL REAL DB)
# =========================================
spring.datasource.url=jdbc:mysql://localhost:3306/my_pos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


# =========================================
# SECURITY - JWT
# =========================================
security.jwt.secret=c2VjcmV0LXN1cGVyLWxvbmcta2V5LXNob3VsZC1iZS1iYXNlNjQ=
security.jwt.expiration-ms=3600000
